### ISSUE TITLE
error: could not create '/Library/Python/2.7/site-packages/gurobipy': Permission denied

### ISSUE THREAD

**Issue by kns0617** [siqichen-usc/YYS-optimization#1]
许可证都安装了，检查前置软件都安装了，求助。确实不太懂码。。。

info  : License 442612 written to file /Users/EillenS/gurobi.lic
EillenS@mouningdeMacBook-Pro-2 mac64 % cd /                                    
EillenS@mouningdeMacBook-Pro-2 / % cd Library/gurobi902/mac64
EillenS@mouningdeMacBook-Pro-2 mac64 % python setup.py install
running install
running build
running build_py
running install_lib
creating /Library/Python/2.7/site-packages/gurobipy
error: could not create '/Library/Python/2.7/site-packages/gurobipy': Permission denied
EillenS@mouningdeMacBook-Pro-2 mac64 %

**Comment by kns0617** [comment]
改为python3 install 成功，谢谢指导

另外后续的指令也要相应改为python3

**Comment by kns0617** [comment]
新问题orz 晚安

EillenS@mouningdeMacBook-Pro-2 ~ % cd Downloads/YYS-optimization
EillenS@mouningdeMacBook-Pro-2 YYS-optimization % python3 YYS_time.py Input.xlsx
Running YYS_time.py using argument list ['YYS_time.py', 'Input.xlsx']
Traceback (most recent call last):
 File "YYS_time.py", line 276, in <module>
   optimize(inputFile)
 File "YYS_time.py", line 11, in optimize
   import gurobipy as grb
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gurobipy/__init__.py", line 1, in <module>
   from .gurobipy import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gurobipy/gurobipy.so, 2): Symbol not found: _PyClass_Type
 Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gurobipy/gurobipy.so
 Expected in: flat namespace
in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gurobipy/gurobipy.so
EillenS@mouningdeMacBook-Pro-2 YYS-optimization %

**Comment by siqichen-usc** [comment]
猜测可能与python版本有关...

**Comment by kns0617** [comment]
检索到了类似问题？：https://github.com/Kitt-AI/snowboy/issues/146

**Comment by kns0617** [comment]
我卸载了3.8，然后开jupyter（没在用terminal）重新安装了gurobi numpy pandas那些，然后所有指令后要加--user，最后run成功了！！！开心
